name = "Gusuryak"
uuid = "ed661292-3381-11e9-03bb-7db5e51659a8"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
Millboard = "39ec1447-df44-5f4c-beaa-866f30b4d3b2"

[targets]
test = ["Test", "Jive", "Millboard"]
